name: clickone-automation
channels:
  - pytorch
  - defaults
  - conda-forge
dependencies:
  - bzip2=1.0.8
  - ca-certificates=2024.3.11
  - libffi=3.4.4
  - ncurses=6.4
  - openssl=3.0.13
  - pip=24.0
  - python=3.11.9
  - readline=8.2
  - setuptools=69.5.1
  - sqlite=3.45.3
  - tk=8.6.14
  - tzdata=2024a
  - wheel=0.43.0
  - xz=5.4.6
  - zlib=1.2.13
  - pip:
      - attrs==23.2.0
      - certifi==2024.6.2
      - charset-normalizer==3.3.2
      - click==8.1.7
      - grpcio==1.63.0
      - grpcio-tools==1.63.0
      - h11==0.14.0
      - idna==3.7
      - outcome==1.3.0.post0
      - overrides==7.7.0
      - packaging==24.1
      - protobuf==5.26.1
      - pysocks==1.7.1
      - python-dotenv==1.0.1
      - requests==2.32.3
      - robotframework==7.0.1
      - robotframework-assertion-engine==3.0.3
      - robotframework-browser==18.5.1
      - robotframework-pythonlibcore==4.4.1
      - robotframework-seleniumlibrary==6.4.0
      - selenium==4.21.0
      - sniffio==1.3.1
      - sortedcontainers==2.4.0
      - trio==0.25.1
      - trio-websocket==0.11.1
      - typing-extensions==4.12.2
      - urllib3==2.2.1
      - wrapt==1.16.0
      - wsproto==1.2.0
