name: Automation Checks

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  agencia-clickone:
    name: Automation for agencia-clickone
    runs-on: ubuntu-latest
    timeout-minutes: 5
    container:
      image: clickoneagencia/automation:latest
      options: --user root

    steps:
      - name: Checkout branch
        uses: actions/checkout@v2
        with:
          path: automation
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Run automation tests
        run: ./automation/run_tests.sh -S ${{ env.INPUT_SRC }}
        env:
          INPUT_SRC: automation  # Set SRC environment variable if needed
