name: Automation Checks

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  agencia-clickone:
    name: Automation for agencia-clickone
    runs-on: ubuntu-latest
    timeout-minutes: 5

    # services:
    #   selenium:
    #     image: selenium/standalone-chrome:latest
    #     ports:
    #       - 4444:4444
    #     options: --shm-size="2g"

    steps:
      - name: Checkout branch
        uses: actions/checkout@v2
        with:
          path: automation
      - uses: nanasess/setup-chromedriver@v2
      - run: |
          export DISPLAY=:99
          chromedriver --url-base=/wd/hub &
          sudo Xvfb -ac :99 -screen 0 1280x1024x24 > /dev/null 2>&1 & # optional
      - name: Setup environment
        uses: mamba-org/setup-micromamba@v1
        with:
          environment-file: automation/environment.yml
          cache-environment: true
          cache-downloads: true
          init-shell: >-
            bash
          post-cleanup: 'all'
      - name: Run Validations
        run: |
          robot -d results automation/Tests
        shell: bash -el {0}
