name: Automation Checks

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  agencia-clickone:
    name: Automation for agencia-clickone
    runs-on: ubuntu-latest
    timeout-minutes: 5
    container:
      image: clickoneagencia/automation:latest
      options: --user root

    steps:
      - name: Checkout branch
        uses: actions/checkout@v2
        with:
          path: automation
      - name: Install dependencies
        run: pip3.11 install -r automation/requirements.txt
      - name: Run Validations
        run: |
          robot -d results automation/Tests
        shell: bash -el {0}
