name: Automation Checks

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  agencia-clickone:
    name: Automation for agencia-clickone
    runs-on: ubuntu-latest
    timeout-minutes: 5
    container:
      image: clickoneagencia/automation:latest
      options: --user root

    steps:
      - name: Checkout branch
        uses: actions/checkout@v2
        with:
          path: automation
      - name: Run automation tests
        run: ./run_tests.sh
        env:
          INPUT_SRC: automation  # Set SRC environment variable if needed
          INPUT_TEST_MODULES: ""
