name: Automation Checks

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  schedule:
    - cron: "0 */6 * * *"
concurrency:
  group: automation-${{ github.ref }}
  cancel-in-progress: true

permissions:
  id-token: write
  contents: write
  pages: write

jobs:
  build-and-test:
    name: Automation
    runs-on: ubuntu-latest
    strategy:
      matrix:
        browser: [chrome]
        client: [agenciaclickone, fracturasyfracturas]
    timeout-minutes: 5

    steps:
      - name: Checkout branch
        uses: actions/checkout@v2
        with:
          path: automation
      - name: Run automation tests
        run: |
          cd automation
          ./run_tests.sh -S ${{ env.INPUT_SRC }} -B ${{ matrix.browser }} -C ${{ matrix.client }}
        env:
          INPUT_SRC: automation
      # - name: Upload test results
      #   uses: actions/upload-artifact@v4
      #   with:
      #     name: github-pages
      #     path: automation/results/
