name: Playwright Tests
on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
jobs:
  e2e:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        test-file:
          - agencia-clickone
          - inkmantattoo47
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: lts/*
    - name: Install dependencies
      run: npm install
    - name: Install Playwright Browsers
      run: npx playwright install --with-deps
    - name: Run Playwright tests
      run: npx playwright test e2e/${{ matrix.test-file }}.spec.ts  --reporter=html,json
    - name: Upload report artifact
      uses: actions/upload-artifact@v4
      with:
        name: report-${{ matrix.test-file }}
        path: playwright-report/
        retention-days: 1

  merge-reports:
    runs-on: ubuntu-latest
    needs: e2e
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - name: Install Playwright
        run: npm install @playwright/test

      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: ./all-reports

      - name: Merge Playwright reports
        run: |
          npx playwright merge-reports --reporter=html ./all-reports/*

      - name: Upload artifact for Pages
        uses: actions/upload-pages-artifact@v3
        with:
          path: playwright-report

  deploy:
    runs-on: ubuntu-latest
    needs: merge-reports
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4

