name: Playwright Tests
on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
jobs:
  e2e:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        test-file:
          - agencia-clickone
          - inkmantattoo47
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: lts/*
    - name: Install dependencies
      run: npm install
    - name: Install Playwright Browsers
      run: npx playwright install --with-deps
    - name: Run Playwright tests
      run: npx playwright test e2e/${{ matrix.test-file }}.spec.ts  --reporter=blob
    - name: Upload blob artifact
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: blob-${{ matrix.test-file }}
        path: blob-report/
        retention-days: 15
